module.exports.FILM_NOT_FOUND_MESSAGE = 'Фильм по указанному _id не найден';
module.exports.USER_NOT_FOUND_MESSAGE = 'Пользователь по указанному _id не найден';
module.exports.DELETE_NOT_OWN_FILM_MESSAGE = 'Чужой фильм удалить нельзя';
module.exports.BAD_REQUEST = 'Переданы некорректные данные';
module.exports.DOUBLE_USER_MESSAGE = 'Пользователь уже существует';
module.exports.DOUBLE_EMAIL_MESSAGE = 'Пользователь с данным email уже существует';
module.exports.NO_AUTH_MESSAGE = 'Необходима авторизация';
module.exports.NO_LOGIN_MESSAGE = 'Неправильные почта или пароль';
module.exports.INTERNAL_SERVER_ERROR = 'На сервере произошла ошибка';
